apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: eshop-apis
  labels:
    app.kubernetes.io/name: basket-api
    app.kubernetes.io/part-of: eshop
    tier: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: basket-api
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: grpc
    port: 81
    targetPort: 81

