apiVersion: v1
kind: Secret
metadata:
  name: eshop-db-secrets
  labels:
    app.kubernetes.io/part-of: eshop
type: Opaque
stringData:
  CatalogDb: "Server=sqldata.eshop-data.svc.cluster.local;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word"
  IdentityDb: "Server=sqldata.eshop-data.svc.cluster.local;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word"
  OrderingDb: "Server=sqldata.eshop-data.svc.cluster.local;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word"
  WebhooksDb: "Server=sqldata.eshop-data.svc.cluster.local;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User Id=sa;Password=Pass@word"
  EventBusUserName: "guest"
  EventBusPassword: "guest"
  SA_PASSWORD: "Pass@word"

