apiVersion: apps/v1
kind: Deployment
metadata:
  name: nosqldata
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: nosqldata
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nosqldata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nosqldata
        app.kubernetes.io/part-of: eshop
        tier: data
    spec:
      containers:
      - name: nosqldata
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nosqldata-pvc
