apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nosqldata-pvc
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: nosqldata-pvc
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

