apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: seq
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seq
        app.kubernetes.io/part-of: eshop
        tier: data
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SEQ_FIRSTRUN_ADMINPASSWORD
          value: Pass@word

