apiVersion: v1
kind: Service
metadata:
  name: sqldata
  namespace: eshop-data
  labels:
    app.kubernetes.io/name: sqldata
    app.kubernetes.io/part-of: eshop
    tier: data
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sqldata
  ports:
  - name: sql
    port: 1433
    targetPort: 1433

