{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webmvc.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "webmvc.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
